<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EventPlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventPlaceRepository extends EntityRepository
{
    public function getInfos()
    {

    }

    public function findPaginated(int $rows, int $offset)
    {
       return $this->createQueryBuilder('e')
            ->select('e.capacity', 'e.geoPoint', 'e.capacity', 'e.id')
            ->getQuery()
            ->setFirstResult($offset)
            ->setMaxResults($rows)
            ->getResult();
    }
}
