<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EventPlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventPlaceRepository extends EntityRepository
{

    public function findPaginated(int $rows = null, int $offset = null)
    {
       return $this->createQueryBuilder('e')
            ->select('e.hints', 'e.geoPoint', 'e.capacity', 'e.id')
            ->join('e.stationsClosest', 'sc')
            ->getQuery()
            ->setFirstResult($offset)
            ->setMaxResults($rows)
            ->getResult();
    }

    public function getFrequenciesAndId()
    {
        return $this->createQueryBuilder('e')
            ->select('e.id', 'e.frequency')
            ->andWhere('e.frequency IS NOT NULL')
            ->getQuery()
            ->getResult();
    }
}
