<?php

namespace AppBundle\Repository;

/**
 * LivingPlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivingPlaceRepository extends \Doctrine\ORM\EntityRepository
{

    public function getInfos()
    {
       return $this->createQueryBuilder('l')
            ->select('l.coordinates', 'l.activityCode', 'l.area', 'l.id', 'l.district', 'l.wayType', 'l.situation')
           ->getQuery()
           ->getResult();
    }

    public function findPaginated(int $rows = null, int $offset = null)
    {
        return $this->createQueryBuilder('l')
            ->select('l.coordinates', 'l.frequency')
            ->where('l.frequency IS NOT NULL')
            ->getQuery()
            ->setFirstResult($offset)
            ->setMaxResults($rows)
            ->getResult();
    }
}
