<?php

namespace AppBundle\Repository;

/**
 * StationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StationRepository extends \Doctrine\ORM\EntityRepository
{

    public function getInfos()
    {
        return $this->createQueryBuilder('s')
            ->select('s.coordinates', 's.frequency')
            ->where('s.frequency IS NOT NULL')
            ->getQuery()
            ->getResult();
    }
}
