<?php

namespace AppBundle\Repository;

/**
 * StationTraficRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StationTraficRepository extends \Doctrine\ORM\EntityRepository
{
}
