<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TouristicPlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TouristicPlaceRepository extends EntityRepository
{

    public function getInfos()
    {
        return $this->createQueryBuilder('t')
            ->select('t.frequency', 't.geoPoint2d')
            ->getQuery()
            ->getResult();
    }

    public function findPaginated(int $rows, int $offset)
    {
       return $this->createQueryBuilder('t')
        ->select('t.frequency', 't.geoPoint2d')
        ->getQuery()
        ->setFirstResult($offset)
        ->setMaxResults($rows)
        ->getResult();
    }
}
