<?php

namespace AppBundle\Repository;

/**
 * TouristicPlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TouristicPlaceRepository extends \Doctrine\ORM\EntityRepository
{
}
