app:
    resource: "@AppBundle/Controller/Api"
    type:     annotation
    prefix: /api/v1

landing:
    resource: "@AppBundle/Controller/DefaultController.php"
    type: annotation

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }
