front:
    resource: "@AppBundle/Controller/Front"
    type:     rest
    prefix:   /api

admin:
    resource: "@AppBundle/Controller/Admin"
    type: rest
    prefix: /api/admin/

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /api

api_login_check:
    path: /api/login_check
