# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        main:
            entity:
                class: AppBundle:User
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/api/admin/
            stateless: true
            guard:
                authenticators:
                    - app.jwt_authenticator
                entry_point: app.jwt_authenticator

    access_control:
        - { path: ^/api/authenticate, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/, role: ROLE_USER }
        - { path: ^/api/doc, role: IS_AUTHENTICATED_ANONYMOUSLY }
