services:
    app.transport_service:
        class: AppBundle\Services\TransportService
        arguments: ['@doctrine.orm.entity_manager']

    app.touristic_service:
        class: AppBundle\Services\TouristicService
        arguments: ['@doctrine.orm.entity_manager']

    app.compute_data_command:
        class: AppBundle\Command\AppComputeDataCommand
        arguments: ['@app.transport_service']

    app.jwt_authenticator:
        class: AppBundle\Security\JWTAuthenticator
        arguments:
            - "@router"
            - "@doctrine.orm.entity_manager"
            - "@app.jwt_manager"

    app.jwt_manager:
        class: AppBundle\Services\JWTManager
        arguments: ["%jwt_private_key%"]
